# Generated by Django 5.0 on 2023-12-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='details',
        ),
    ]
